INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(101,'INFOSIS',700.50);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(102,'TCS',800.75);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(103,'MRK',90000.50);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(104,'TESLA',80000.75);

