management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 2222
spring:
  application:
    name: CLIENT-TWO
    
  boot:
    admin:
      client:
        url: http://localhost:9090/