management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 3333
spring:
  application:
    name: CLIENT-TWO
  boot:
    admin:
      client:
        url: http://localhost:1111/

